### ISSUE TITLE
Create a 63 milestone page on the wiki

### ISSUE THREAD

**Issue by pascalchevrel** [pascalchevrel/rm_63#2]
- [ ] Create the page at https://wiki.mozilla.org/Releases/Firefox_63
- [ ] Create and link to a draft release note gdoc
- [ ] Create and link to a timeline gdoc
- [ ] Create a worry list etherpad like liz at https://public.etherpad-mozilla.org/p/firefox63-worry-list
- [ ] Create a template checklist for the release
